version: '3'
services:
  php:
    build:
      context: ./dockers/php
    volumes:
      - './src:/var/www/html'

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './src:/var/www/html'
      - './dockers/nginx/conf.d:/etc/nginx/conf.d'
    depends_on:
      - php

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: lara
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: andrew
      MYSQL_PASSWORD: password1
    volumes:
      - './dockers/volume/mysql:/var/lib/mysql'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5